### ISSUE TITLE
TCP sees only one invertor

### ISSUE THREAD

**Issue by GerwinGeukes** [klaasnicolaas/python-omnikinverter#370]
I have a Omnik WiFi kit with 2 4ktl2 invertors.they are connected with RS485.Your bot is awesome only converts the first invertor. In the HS log from the Omnik all data from the first are shown. I cannot give the invertor serial number starting with NLBL... it allows only digits. The serial of the WiFi kit runs.

**Comment by MarijnS95** [comment]
Can you by chance perform and provide a network capture when the inverter tries to broadcast this info to the internet (omnikportal / solarman)? The format is pretty much identical to what we parse, so that we can have a look and understand what is going on :)

**Comment by GerwinGeukes** [comment]
Where/ how can I grab the data whitehark did not work.

**Comment by MarijnS95** [comment]
Wireshark would be the place to go; make sure you're connected to the network via a hub rather than a switch so that all packets are also seen by the adapter of your monitoring PC. Alternatively connect the WiFi kit to a wireless AP hosted on a computer where you can run wireshark to intercept all traffic.

Last approach is to use Wireshark to intercept the traffic between this package (`python-omnikinverter`) and the WiFi kit: perhaps the reply is in a separate message but we simply don't read it. For that I also have an updated version of this package to test out, which I hope to submit in a PR soon: https://github.com/MarijnS95/python-omnikinverter/tree/tcp-parse-from-stream

**Comment by GerwinGeukes** [comment]
Marijn,

Ik kan alleen de ARP request in het netwerksegment zien over de IP van de client.De eigen verzonden TCP data kan ik niet van uit de host via wireshark vinden. Als ik op de de wifi kit inlog dan zie ik veel data gegenereerd worden op HTTP: etc. Ik weet dat de kit data verstuurd er is logging.

Ik ga nu kijken of if vanuit het andre segment waar de HS staat of daar data komt..

Gerwin

**Comment by GerwinGeukes** [comment]
Martijn,

Ik heb op beide netwerksegmenten (hoofd en IOT netwerk) geprobeerd met wireshark te analyseren helaas het is niet 1 op 1 uit te lezen. Alle communicatie loopt via VLAN's zichtbaar. Ik heb geprobeerd met een simple native switch, maar zonder internet stuurt de kit niets weg. Remote host is not pingable. 
Op de WiFi kit heeft een internal server 172.16.75.14 TCP port 8899 staat de data die van RS232/485 komt. Heb je een idee hoe dat is te gebruiken?


Gerwin

**Comment by MarijnS95** [comment]
Erwin,

Zou je een wireshark capture kunnen maken terwijl je dit python package gebruikt om de inverter via TCP (poort 8899) uit te lezen?

Uit je eerste bericht begrijp ik dat je maar één van de twee serial number in kan vullen; volgens het dataformaat zou deze echter altijd een getal moeten zijn, en ik denk dat de `NLBL...` het serial van de WiFi kit is (of van een ander component van de inverter)? Op mijn 3k-TL kan ik via de fysieke knop door alle variabelen heen stappen op het mini-display, en ergens na `Set language` komt het numerieke serienummer in beeld. Zou je kunnen kijken of je voor je andere inverter ook het numerieke S/N kan vinden?

Mijn inverter leek geen problemen te hebben met een willekeurig serienummer in de request, en stuurde toch altijd een reply terug, maar misschien gebruikt de WiFi kit dit om de juiste inverter te addresseren. Maar er is ook een kans dat deze de data van beide inverters terugstuurt, of dat een van de momenteel nog onbekende bits/bytes in de request/reply hier verantwoordelijk voor zijn.

Voor het gemak zou je kunnen kijken of je mijn branch werkend krijgt die constant data van de inverter uitleest: misschien vinden we hier wel twee pakketjes in terug. In het kort moet je [Python en Poetry](https://github.com/klaasnicolaas/python-omnikinverter#setting-up-development-environment) (en git) installeren. Daarna mijn branch lokaal clonen en de volgende hulpstappen gebruiken:

```shell
git clone https://github.com/MarijnS95/python-omnikinverter --branch tcp-parse-from-stream

cd python-omnikinverter

# Install python dependencies via poetry
poetry install
```

Nu moet je in `examples/test_output_tcp.py` `examples.com` vervangen met het IP adres van je WiFi kit. Dan ook het serienummer `123456789` met die van één van je inverters.

Dan kun je het test-script uitvoeren en de output en debug-logging met ons delen, in de hoop dat we hier iets nuttigs uit kunnen halen (maar een wireshark capture is misschien makkelijker, en geeft ons meer informatie).

```shell
poetry run python ./examples/test_output_tcp.py
```

**Comment by GerwinGeukes** [comment]
Marijn,

De SN van de investors zijn NLBL… op de inverter. De datatrings op de oude omink omgeving stonden de serienummers met NLBL etc geregistreerd. De gegrabde  data is van een inverter.  
Jouw GitHub code installeert goed. Ik heb wat moeite om de dependenties via poetry te installeren. Poetry install start niet het commando is niet vinden. 
en kan de examples/test _output_tcp.py file niet vinden. 

Dus,

Gerwin

**Comment by MarijnS95** [comment]
Er zijn inderdaad meerdere "typen" serienummer. die in de header van de packets zijn numeriek met meestal 8 of 9 getallen, de textuele S/Ns die met `NLBL...` of `NLDN...` beginnen zijn weer wat anders.

Waar loop je precies tegenaan met het commando? Heb je Poetry geïnstalleerd via https://python-poetry.org/docs/? Het file staat nog steeds op dezelfde plek:

https://github.com/MarijnS95/python-omnikinverter/blob/tcp-parse-from-stream/examples/test_output_tcp.py

Maar dat gaat misschien ooit veranderen als ik deze branch update naar de meest recente `main`, daar is het `examples/test_tcp.py` geworden.
